/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mykingdom.mupdf;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

@Kroll.module(name = "Mupdf", id = "com.mykingdom.mupdf")
public class MupdfModule extends KrollModule {

	// Standard Debugging variables
	private static final String TAG = "MupdfModule";
	
	// You can define constants with @Kroll.constant, for example:
	@Kroll.constant public static final int DIRECTION_VERTICAL = 0;
	@Kroll.constant public static final int DIRECTION_HORIZONTAL = 1;

	public MupdfModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}
}
